import { Sakura } from '@/components/deco/Sakura';
import { IconChevronLeft } from '@/components/ui/Icon';
import { Colors, FontFamily, FontSize, Radius, Spacing ,sf } from '@/constants/theme';
import { useIPad } from '@/hooks/use-ipad';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

export default function PrivacyScreen() {
  const insets = useSafeAreaInsets();
  const { column } = useIPad();
  return (
    <View style={[styles.screen, { paddingTop: insets.top }]}>
      <View style={styles.decoTR} pointerEvents="none"><Sakura size={26} color={Colors.sakura} /></View>
      <View style={styles.decoBR} pointerEvents="none"><Sakura size={18} color={Colors.sakura} /></View>
      <View style={[styles.header, column]}>
        <Pressable style={styles.backBtn} onPress={() => router.back()} id="privacy-back">
          <IconChevronLeft size={14} color={Colors.ink2} />
        </Pressable>
        <Text style={styles.title}>Privacy Policy</Text>
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={[styles.content, column]}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.updated}>Last updated: September 14, 2026</Text>

        <Section title="1. Your private journal stays on your device">
          Ships, headcanons, letters, scenes, and anything else you create outside the community
          feature are stored locally in an on-device database. We cannot see it, access it, or
          back it up. Deleting the App removes all of it permanently. None of this is affected by
          anything below.
        </Section>

        <Section title="2. Creating a community account">
          To use posts, groups, or public profiles, you create an account with an email address.
          Authentication is handled by our database provider, Supabase — we never see or store
          your password ourselves. Supabase's privacy policy: supabase.com/privacy.
        </Section>

        <Section title="3. What the community feature stores on our servers">
          Once you use the community feature, this is stored on Supabase's servers, not just your
          device: your profile (name, username, pronouns, bio, about section, avatar and gallery
          photos, theme songs, flags, blinkie wall text, DNI text), any F/O profile you publish
          publicly, posts, comments, likes, poll votes and bingo cards, groups you create or join
          and messages you send in them, who you follow and who follows you, anyone you've
          blocked, reports you file, and notifications generated by activity on your account.
        </Section>

        <Section title="4. What's public">
          A published community profile, its posts, and its F/O profiles are visible to other
          signed-in users, and — if you enable public profiles — to anyone with the link,
          including on our website. Your private, on-device journal is never included in this.
        </Section>

        <Section title="5. Reports and moderation">
          If you report a post, comment, message, or profile, we store the report so we can
          review it, usually within 24–48 hours. We don't share who filed a report with the
          person being reported.
        </Section>

        <Section title="6. Blocking">
          Blocking another user hides their content from you and yours from them. We keep a
          record of the block so it keeps working.
        </Section>

        <Section title="7. Subscriptions">
          When you subscribe, our payment processor (RevenueCat) receives a pseudonymous ID and
          your purchase receipt to verify your subscription status. No personal details from your
          community account are shared with RevenueCat. RevenueCat's privacy policy:
          revenuecat.com/privacy.
        </Section>

        <Section title="8. Notifications">
          Reminders from your private journal are handled entirely on-device. Community
          notifications (likes, comments, follows, group messages) are delivered through Apple's
          push service based on activity on your account.
        </Section>

        <Section title="9. Age requirement">
          The community feature is intended for users aged 17 and up, consistent with the app's
          App Store age rating. We don't knowingly collect data from children under 13.
        </Section>

        <Section title="10. Deleting your data">
          You can delete individual posts, comments, or your account at any time from within the
          app. Deleting your account removes your profile, posts, and comments from our servers.
          Your private, on-device journal is deleted the same way it's always been — from
          Settings, or by deleting the app.
        </Section>

        <Section title="11. Contact">
          Questions, or want your data deleted? Reach us at: ashwinnanbazhagan@gmail.com
        </Section>
      </ScrollView>
    </View>
  );
}

function Section({ title, children }: { title: string; children: string }) {
  return (
    <View style={s.section}>
      <Text style={s.heading}>{title}</Text>
      <Text style={s.body}>{children}</Text>
    </View>
  );
}

const s = StyleSheet.create({
  section: { marginBottom: Spacing.s4 },
  heading: {
    fontFamily: FontFamily.uiSemiBold, fontSize: sf(13), color: Colors.ink,
    marginBottom: 6,
  },
  body: {
    fontFamily: FontFamily.ui, fontSize: FontSize.caption,
    color: Colors.ink2, lineHeight: 22,
  },
});

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.paper },
  decoTR: { position: 'absolute', top: 130, right: 16 },
  decoBR: { position: 'absolute', bottom: 100, right: 20 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.s3,
    paddingHorizontal: Spacing.s5, paddingTop: Spacing.s3, paddingBottom: Spacing.s3,
    borderBottomWidth: 1, borderBottomColor: Colors.line,
  },
  backBtn: {
    width: 32,
    height: 32,
    borderRadius: Radius.pill,
    backgroundColor: Colors.vellum,
    borderWidth: 1,
    borderColor: Colors.line,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  title: {
    fontFamily: FontFamily.displayItalic, fontSize: sf(22), color: Colors.ink, flex: 1,
  },
  scroll: { flex: 1 },
  content: {
    paddingHorizontal: Spacing.s5, paddingTop: Spacing.s4, paddingBottom: Spacing.s9,
  },
  updated: {
    fontFamily: FontFamily.ui, fontSize: sf(11), color: Colors.ink3,
    marginBottom: Spacing.s4,
  },
});
