import React from 'react';

export const Privacy: React.FC = () => {
  return (
    <main className="page-container">
      <div className="container">
        <article className="content-card">
          <h1>Privacy Policy</h1>
          <div className="content-meta">Last updated: September 14, 2026</div>

          <p>
            YumeShip has two parts: a private journal that lives entirely on your device, and an
            optional community feature (profiles, posts, groups) that runs on our servers. This
            policy explains what happens with each.
          </p>

          <h2>1. Your private journal stays on your device</h2>
          <p>
            Ships, headcanons, letters, scenes, and anything else you create outside the community
            feature are stored locally in an on-device database. We cannot see it, access it, or
            back it up. Deleting the app removes all of it permanently. None of this is affected by
            anything below.
          </p>

          <h2>2. Creating a community account</h2>
          <p>
            To use posts, groups, or public profiles, you create an account with an email address.
            Authentication is handled by our database provider, Supabase — we never see or store
            your password ourselves. Supabase's privacy policy:{' '}
            <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer">
              supabase.com/privacy
            </a>.
          </p>

          <h2>3. What the community feature stores on our servers</h2>
          <p>Once you use the community feature, the following is stored on Supabase's servers, not just your device:</p>
          <ul>
            <li>Your profile: name, username, pronouns, bio, about section, avatar and gallery photos, theme songs, flags, blinkie wall text, and any "do not interact" (DNI) text you add</li>
            <li>Any F/O profile you choose to publish publicly, and its own content (name, photos, tagline, about, gallery)</li>
            <li>Posts, comments, likes, poll votes, and bingo cards you create</li>
            <li>Groups you create or join, and the messages you send in group chats</li>
            <li>Who you follow, who follows you, and anyone you've blocked</li>
            <li>Reports you file, and the reason and details you include with them</li>
            <li>Notifications generated by activity on your account (likes, comments, follows, mentions)</li>
          </ul>

          <h2>4. What's public</h2>
          <p>
            A published community profile, its posts, and its F/O profiles are visible to other
            signed-in users, and — if you enable public profiles — to anyone with the link,
            including on our website. Photos and images you upload to the community feature are
            stored in a way that's reachable by anyone who has the file's address, the same way
            most social apps host images. Your private, on-device journal is never included in any
            of this.
          </p>

          <h2>5. Reports and moderation</h2>
          <p>
            If you report a post, comment, message, or profile, we store the report (what you
            reported, why, and any details you added) so we can review it. We aim to review reports
            within 24–48 hours. We don't share the identity of who filed a report with the person
            being reported.
          </p>

          <h2>6. Blocking</h2>
          <p>
            Blocking another user hides their content from you and yours from them. We keep a
            record of the block so it keeps working — it isn't shared with the blocked user beyond
            them no longer seeing your content.
          </p>

          <h2>7. Subscriptions</h2>
          <p>
            When you subscribe, our payment processor (RevenueCat) receives a pseudonymous ID and
            your purchase receipt to verify your subscription status. No personal details from your
            community account are shared with RevenueCat. RevenueCat's privacy policy:{' '}
            <a href="https://www.revenuecat.com/privacy" target="_blank" rel="noopener noreferrer">
              revenuecat.com/privacy
            </a>.
          </p>

          <h2>8. Notifications</h2>
          <p>
            If you allow notifications, reminders from your private journal are handled entirely
            on-device. Community notifications (likes, comments, follows, group messages) are
            delivered through Apple's push notification service based on activity on your account.
          </p>

          <h2>9. Age requirement</h2>
          <p>
            The community feature is intended for users aged 17 and up, consistent with the app's
            App Store age rating. We don't knowingly collect data from children under 13. If you
            believe a child has created an account, contact us and we'll remove it.
          </p>

          <h2>10. Deleting your data</h2>
          <p>
            You can delete individual posts, comments, or your account at any time from within the
            app. Deleting your account removes your profile, posts, and comments from our servers.
            Your private, on-device journal is deleted the same way it's always been — from
            Settings, or by deleting the app. Content you've already reported, or that others have
            already seen or saved, may not be fully removable from other people's devices.
          </p>

          <h2>11. Changes to this policy</h2>
          <p>
            If this policy changes in a way that matters — like a new category of data being
            collected — we'll update the date above and, where required, notify you in the app.
          </p>

          <h2>12. Contact</h2>
          <div className="contact-box">
            <p>Questions, or want your data deleted? Reach us at:</p>
            <p>
              <a href="mailto:support@myyume.app">
                <strong>support@myyume.app</strong>
              </a>
            </p>
          </div>
        </article>
      </div>
    </main>
  );
};
